Update

diff --git a/docker/ubuntu16/Dockerfile b/docker/ubuntu16/Dockerfile
--- a/docker/ubuntu16/Dockerfile
+++ b/docker/ubuntu16/Dockerfile
@@ -4,17 +4,16 @@
 FROM ubuntu:18.04
 
 ARG JENKINS_HOME=${JENKINS_HOME:-/home/jenkins}
-
 ARG JDK8_VERSION=${JDK8_VERSION:-172}
-ARG JAVA_URL="http://home.nabla.mobi/download/jdk/jdk-8u${JDK8_VERSION}-linux-x64.tar.gz"
+ARG JAVA_URL="http://fr1cslfrbm0059.misys.global.ad/download/jdk/jdk-8u${JDK8_VERSION}-linux-x64.tar.gz"
 ENV JDK_HOME=${JDK_HOME:-"/usr/local/jdk1.8.0_${JDK8_VERSION}"}
 ENV JAVA_HOME=${JAVA_HOME:-$JDK_HOME}
-ARG CERT_NAME="NABLA.crt"
-ARG CERT_URL="http://home.nabla.mobi/download/certs/UK1VSWCERT01-CA-5.crt"
+ARG CERT_NAME="UK1VSWCERT01-CA-5.crt"
+ARG CERT_URL="http://fr1cslfrbm0059.misys.global.ad/download/certs/UK1VSWCERT01-CA-5.crt"
 
 #MAINTAINER Alban Andrieu "https://github.com/AlbanAndrieu"
 #LABEL vendor="TEST" version="1.0.0"
-LABEL description="Image used by nabla products to build Java/Javascript and CPP\
+LABEL description="Image used by fusion-risk products to build Java/Javascript and CPP\
  this image is running on Ubuntu 16.04."
 
 # Volume can be accessed outside of container
@@ -129,13 +128,10 @@ RUN echo '{ "allow_root": true }' > /root/.bowerrc
 RUN ./clean.sh
 RUN chown -R jenkins:$(id -gn jenkins) $JENKINS_HOME && chmod -R 777 $JENKINS_HOME
 
-# Execute
-#RUN ansible-galaxy install -r $WORKDIR/requirements.yml -p $WORKDIR/roles/ --ignore-errors \
-# && ansible-playbook $WORKDIR/jenkins-slave.yml -i $WORKDIR/hosts -c local -vvvv -e "jenkins_ssh_key_file={{ jenkins_home }}/.ssh/id_rsa" -e "workspace=/tmp"
-
 # drop back to the regular jenkins user - good practice
 USER jenkins
 ENV HOME=${JENKINS_HOME}
+# && chmod -R 777 ${HOME}/.npm && chmod -R 777 ${HOME}/.m2
 # && mkdir ${HOME}/.config && mkdir ${HOME}/.local
 RUN mkdir ${HOME}/workspace && mkdir ${HOME}/.sonar && mkdir -p ${HOME}/.m2/repository && chmod -R 777 ${HOME}
 #RUN id jenkins && ls -lrtai $HOME/ && ls -lrtai $HOME/.sonar
@@ -162,63 +158,65 @@ CMD ["/bin/bash"]
 
 ## This Dockerfile is used to build an image containing basic stuff to be used as a Jenkins slave build node.
 #FROM tomcat:8-jre8 as runner
-#
-#MAINTAINER Alban Andrieu "https://github.com/AlbanAndrieu"
-#
-#LABEL vendor="TEST" version="1.0.0"
-#LABEL description="Image used by nabla products to build Java/Javascript and CPP\
-# this image is running on Ubuntu 16.04."
-#
-#ARG JENKINS_HOME=${JENKINS_HOME:-/home/jenkins}
-#
-##ENV LANG en_US.UTF-8
-#ENV TERM="xterm-256color"
-#
-##USER 0
-#
-#RUN printf "\033[1;32mFROM JENKINS_HOME: ${JENKINS_HOME} \033[0m\n"
-#
-## Install ansible
-#RUN apt-get clean && apt-get -y update && apt-get install -y \
-#    -o APT::Install-Recommend=false -o APT::Install-Suggests=false \
-#    $BUILD_PACKAGES git zip unzip python-yaml python-jinja2 python-pip openssh-server rsyslog \
-#	&& apt-get install -y xz-utils wget curl lsof sshpass \
-#	net-tools iputils-ping x11-apps
-#
-##RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - ;\
-##    apt-get update && apt-get install -y nodejs ;\
-##    npm set progress=false && \
-##    npm config set depth 0 && \
-##    npm install -g bower grunt grunt-cli nsp
-#
-## Copy to images tomcat path
-##ADD web.xml /usr/local/tomcat/conf/
-##ADD obclient.properties /etc/
-##ADD WebClient.properties /etc/
-#
-##COPY --chown=jenkins:$(id -gn jenkins) --from=builder $JENKINS_HOME/target/*.war /usr/local/tomcat/webapps/
-##COPY --chown=jenkins:$(id -gn jenkins) --from=0 $JENKINS_HOME/target/*.war /usr/local/tomcat/webapps/
-##ADD ./target/test.war /usr/local/tomcat/webapps/
-#COPY --from=0 $JENKINS_HOME/target/test.war $CATALINA_HOME/webapps/test.war
-##COPY target/test.war $CATALINA_HOME/webapps/test.war
-#
-## Clean up APT when done.
-#RUN apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
-#&& ifconfig | awk '/inet addr/{print substr($2,6)}' ## Display IP address (optional)
-#
-## Standard SSH port AND 8080
-##EXPOSE 22
-#EXPOSE 22 8080
-#
-## set a health check
-#HEALTHCHECK --interval=1m \
-#            --timeout=5s \
-#CMD curl -f http://127.0.0.1:8080 || exit 1
-##CMD wget --quiet --tries=1 --spider http://localhost:8080/wizard/ || exit 1
-#
-##CMD ["/usr/sbin/sshd", "-D"]
-#CMD ["/bin/bash"]
-##CMD ["-g", "deamon off;"]
-#
-##docker build --tag mywebserver .
-##docker run -it --rm -p 8888:8080 mywebserver
+FROM tomcat:8-jre8
+#FROM tomcat:9.0-jre8-alpine
+
+MAINTAINER Alban Andrieu "https://github.com/AlbanAndrieu"
+
+LABEL vendor="TEST" version="1.0.0"
+LABEL description="Image used by fusion-risk products to build Java/Javascript and CPP\
+ this image is running on Ubuntu 16.04."
+
+ARG JENKINS_HOME=${JENKINS_HOME:-/home/jenkins}
+
+#ENV LANG en_US.UTF-8
+ENV TERM="xterm-256color"
+
+#USER 0
+
+RUN printf "\033[1;32mFROM JENKINS_HOME: ${JENKINS_HOME} \033[0m\n"
+
+# Install ansible
+RUN apt-get clean && apt-get -y update && apt-get install -y \
+    -o APT::Install-Recommend=false -o APT::Install-Suggests=false \
+    $BUILD_PACKAGES git zip unzip python-yaml python-jinja2 python-pip openssh-server rsyslog \
+	&& apt-get install -y xz-utils wget curl lsof sshpass \
+	net-tools iputils-ping x11-apps
+
+#RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - ;\
+#    apt-get update && apt-get install -y nodejs ;\
+#    npm set progress=false && \
+#    npm config set depth 0 && \
+#    npm install -g bower grunt grunt-cli nsp
+
+# Copy to images tomcat path
+#ADD web.xml /usr/local/tomcat/conf/
+#ADD obclient.properties /etc/
+#ADD WebClient.properties /etc/
+
+#COPY --chown=jenkins:$(id -gn jenkins) --from=builder $JENKINS_HOME/target/*.war /usr/local/tomcat/webapps/
+#COPY --chown=jenkins:$(id -gn jenkins) --from=0 $JENKINS_HOME/target/*.war /usr/local/tomcat/webapps/
+#ADD ./target/test.war /usr/local/tomcat/webapps/
+COPY --from=0 $JENKINS_HOME/target/test.war $CATALINA_HOME/webapps/test.war
+#COPY target/test.war $CATALINA_HOME/webapps/test.war
+
+# Clean up APT when done.
+RUN apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
+&& ifconfig | awk '/inet addr/{print substr($2,6)}' ## Display IP address (optional)
+
+# Standard SSH port AND 8080
+#EXPOSE 22
+EXPOSE 22 8080
+
+# set a health check
+HEALTHCHECK --interval=1m \
+            --timeout=5s \
+CMD curl -f http://127.0.0.1:8080 || exit 1
+#CMD wget --quiet --tries=1 --spider http://localhost:8080/wizard/ || exit 1
+
+#CMD ["/usr/sbin/sshd", "-D"]
+CMD ["/bin/bash"]
+#CMD ["-g", "deamon off;"]
+
+#docker build --tag mywebserver .
+#docker run -it --rm -p 8888:8080 mywebserver
