Update hooks

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,49 +1,55 @@
-#!/bin/sh
-#
-# An example hook script to verify what is about to be committed.
-# Called by "git commit" with no arguments.  The hook should
-# exit with non-zero status after issuing an appropriate message if
-# it wants to stop the commit.
-#
-# To enable this hook, rename this file to "pre-commit".
+#!/usr/bin/env bash
+# This is a randomish md5 to identify this script
+# 138fd403232d2ddd5efb44317e38bf03
 
-if git rev-parse --verify HEAD >/dev/null 2>&1
-then
-	against=HEAD
+pushd "$(dirname "$0")" >& /dev/null
+HERE="$(pwd)"
+popd >& /dev/null
+
+retv=0
+args=""
+
+ENV_PYTHON=/usr/bin/python2.7
+SKIP_ON_MISSING_CONF=false
+
+if which pre-commit >& /dev/null; then
+    exe="pre-commit"
+    run_args=""
+elif "$ENV_PYTHON" -c 'import pre_commit.main' >& /dev/null; then
+    exe="$ENV_PYTHON"
+    run_args="-m pre_commit.main"
+elif python -c 'import pre_commit.main' >& /dev/null; then
+    exe="python"
+    run_args="-m pre_commit.main"
 else
-	# Initial commit: diff against an empty tree object
-	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?'
+    exit 1
 fi
 
-# If you want to allow non-ASCII filenames set this variable to true.
-allownonascii=$(git config --bool hooks.allownonascii)
-
-# Redirect output to stderr.
-exec 1>&2
-
-# Cross platform projects tend to avoid non-ASCII filenames; prevent
-# them from being added to the repository. We exploit the fact that the
-# printable range starts at the space character and ends with tilde.
-if [ "$allownonascii" != "true" ] &&
-	# Note that the use of brackets around a tr range is ok here, (it's
-	# even required, for portability to Solaris 10's /usr/bin/tr), since
-	# the square bracket bytes happen to fall in the designated range.
-	test $(git diff --cached --name-only --diff-filter=A -z $against |
-	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
-then
-	cat <<\EOF
-Error: Attempt to add a non-ASCII file name.
-
-This can cause problems if you want to work with people on other platforms.
-
-To be portable it is advisable to rename the file.
-
-If you know what you are doing you can disable this check using:
-
-  git config hooks.allownonascii true
-EOF
-	exit 1
+# Run the legacy pre-commit if it exists
+if [ -x "$HERE"/pre-commit.legacy ] && ! "$HERE"/pre-commit.legacy; then
+    retv=1
 fi
 
-# If there are whitespace errors, print the offending file names and fail.
-exec git diff-index --check --cached $against --
+CONF_FILE="$(git rev-parse --show-toplevel)/.pre-commit-config.yaml"
+if [ ! -f "$CONF_FILE" ]; then
+    if [ "$SKIP_ON_MISSING_CONF" = true -o ! -z "$PRE_COMMIT_ALLOW_NO_CONFIG" ]; then
+        echo '`.pre-commit-config.yaml` config file not found. Skipping `pre-commit`.'
+        exit $retv
+    else
+        echo 'No .pre-commit-config.yaml file was found'
+        echo '- To temporarily silence this, run `PRE_COMMIT_ALLOW_NO_CONFIG=1 git ...`'
+        echo '- To permanently silence this, install pre-commit with the `--allow-missing-config` option'
+        echo '- To uninstall pre-commit run `pre-commit uninstall`'
+        exit 1
+	fi
+fi
+
+
+
+# Run pre-commit
+if ! "$exe" $run_args run $args --config .pre-commit-config.yaml; then
+    retv=1
+fi
+
+exit $retv
